from .usuario import Usuario as UsuarioResource
from .usuario import Usuarios as UsuariosResource
from .libro import Libro as LibroResource
from .libro import Libros as LibrosResource
from .prestamo import Prestamo as PrestamoResource
from .prestamo import Prestamos as PrestamosResource
from .login import Login as LoginResource
from .sign_in import SignIn as SignInResource
from .configuracion import Configuracion as ConfiguracionResource
from .valoracion import Valoracion as ValoracionResource
from .notificaciones import Notificacion as NotificacionResource
from .notificaciones import Notificaciones as NotificacionesResource
from .autor import Autor as AutorResource
from .autor import Autores as AutoresResource
from .asistencia import Asistencias as AsistenciasResource
